# Generated by Django 5.1.7 on 2025-03-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phonenumber', models.CharField(max_length=250)),
                ('session_number', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('remark', models.CharField(default=0, max_length=200)),
                ('reccomendation', models.CharField(blank=True, max_length=250)),
                ('session_time', models.CharField(max_length=250)),
                ('session_date', models.CharField(max_length=250)),
                ('status', models.CharField(default=0, max_length=200)),
                ('counselor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.counselor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patient')),
            ],
            options={
                'db_table': 'session_table',
            },
        ),
    ]
