# Generated by Django 5.1.7 on 2025-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_post_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
